### ISSUE TITLE
Does this plugin boilerplate change with the new npm fix?

### ISSUE THREAD

**Issue by grandmore** [Nopik/serverless-serve#1]
A new npm fix has been added [#367 -Change plugins to load from root level node_modules folder](https://github.com/serverless/serverless/pull/367).

Does this change where this boilerplate gets installed?

**Comment by Nopik** [comment]
No idea yet. Hopefully not. I've just updated this plugin to work with the latest version of the framework, if the patch you mentioned will get merged, I'll make sure that this plugin will work with the new version, too.
