### ISSUE TITLE
Sample App?

### ISSUE THREAD

**Issue by phillip-haydon** [Nopik/serverless-serve#10]
There's not enough info in the Read Me to get started unless you have copious amounts of prior knowledge in (i don't know what).

Would be nice to have a sample app which shows a setup with a couple of lambda's exposed as an API.

(I hope that doesn't sound bad, I just came across this project and it sounds like exactly what I'm looking for and hoping it is, just donno how to get started)

**Comment by Nopik** [comment]
Well, I'm not sure what kind of info you look for. You write your lambdas as usual, you start serve plugin, you send your http requests to the serve plugin, then you profit. There is not much more behind that.

**Comment by phillip-haydon** [comment]
Hey,

Yeah I didn't realise I needed `Serverless`. My bad, it makes sense now. 

Just need to get `Serverless` to fix their bugs on Windows. Can't create a project, let along a project that does not deploy. I already have a nicer deployment process than the stuff that Serverless has but it looks like I need their stuff just to create a local environment to test with :(
