### ISSUE TITLE
endpoint.responses['default'] never chosen if other response possible (like 400)

### ISSUE THREAD

**Issue by dherault** [Nopik/serverless-serve#20]
This:

``` javascript
handler(event, context( fun.name, function(err, result) {
  let response;
  let errResult = result;

  if (err) {
    errResult = { errorMessage: err };
    err = err.toString();
  } else {
    err = '';
  };

  Object.keys(endpoint.responses).forEach(key => {
    if (!response && (key != 'default') && err.match(endpoint.responses[key].selectionPattern)) {
      response = endpoint.responses[key];
    }
  });

  response = response || endpoint.responses['default'];

  resolve(Object.assign({
    result: errResult
  }, response));
}));
```

Always selects the first non-default response of a given endpoint.
The pb comes from `err.match` that always returns an array if `err === ''` and `selectionPattern === undefined`, therefore a truthy value. In my case, it replies 400 instead of 200 just because `err.match(endpoint.responses['400'].selectionPattern)` returns `[ '', index: 0, input: '' ]`.

I can PR this fix if you want:

``` javascript
handler(event, context(fun.name, function(err, result) {
  let response;
  let finalResult;

  if (err) {
    finalResult = { errorMessage: err };
    const errString = err.toString();
    Object.keys(endpoint.responses).forEach(key => {
      if (!response && key !== 'default' && errString.match(endpoint.responses[key].selectionPattern)) {
        response = endpoint.responses[key];
      }
    });
  }
  response = response || endpoint.responses['default'];
  finalResult = finalResult || result;

  resolve(Object.assign({ result: finalResult }, response));
}));
```

**Comment by Nopik** [comment]
The proposed change is not good, I have projects where non-error response is not default (as I keep default to be 500, to make sure that success is explicitly set), and this change would break it.

So far the code assumed that selectionPattern is present on all non-default responses. If you have some valid use case where this would not happen, please reopen this issue and post examples.

**Comment by pho3nixf1re** [comment]
I think this should be expressly mentioned in the documentation somehow as it threw me off for quite awhile getting a new project setup. This behavior is divergent from the AWS environment which is confusing. Upon reflection I like your mentioned setup where you must explicitly label success but that may not be everyone's use case especially seeing as this is not the way a new project is setup to behave making this plugin broken by default with no obvious explanation as to why.

**Comment by pho3nixf1re** [comment]
I also think leaving this open is the correct state as it _is_ a bug and worthy of discussion for a resolution.

**Comment by Nopik** [comment]
Well, actually the current behavior is exactly what I'm observing on APIG, and any changes proposed so far are actually contradicting it. I guess I'll need some more info what exactly is happening in your user cases.

**Comment by Nopik** [comment]
My point is that serve plugin will go toward getting better emulation of APIG over time, as a goal of the project. But, as I said, so current code is the most correct implementation I'm aware about.

**Comment by dherault** [comment]
Reproducing the issue is quite simple:
- Create a new serverless project `sls project create`.
- Create a new component and a new function `sls component create mycomp && sls function create mycomp/myfun`, do not edit the code.
- Deploy it to AWS, call you endpoint: It will answer 200 and the default Serverless response.
- Install serverless-serve, call you emulated endpoint locally, it will answer 400.
- To fix the difference, add an `errorPattern` prop to your 400 response in your `s-function.json`.

**Comment by Nopik** [comment]
Right. Please try v1.5.1.

**Comment by dherault** [comment]
I can't because I'm still using serverless 0.4.x and you commited changes for serverless 0.5.x (not available on npm). I throws a lot on 0.4.x :sob:

**Comment by Nopik** [comment]
Ah, that wasn't intentional, sorry. I'll try to sort this out, as I'm already on v0.5 and serve will switch there as soon as v0.5 will get published.

**Comment by Nopik** [comment]
So, v1.5.2 got published, should work on sls v0.4 but it is not tested, please verify.

**Comment by dherault** [comment]
We're almost there, I'm getting a `TypeError: Cannot read property 'path' of undefined` when calling a tested route

**Comment by Nopik** [comment]
Can you post full stacktrace?

**Comment by dherault** [comment]
There is none because it's logged with Serverless's CLI utility. I'll add a console.log

**Comment by dherault** [comment]
It seems it was within my handler u_u sorry about that. The fix must work, thanks !
