### ISSUE TITLE
Parity with AWS runtime

### ISSUE THREAD

**Issue by eggyal** [Nopik/serverless-serve#21]
This is a great little tool, but it requires Node v4, whereas AWS Lambda is currently only v0.10.13.

Any thoughts about building a simulator that will run on the same runtime as AWS, for better dev/prod parity?  I recognise this won't be achievable as a mere plugin for serverless (since that too requires v4).

At very least, this observation should probably be added to the [Simulation quality](https://github.com/Nopik/serverless-serve#simulation-quality) footnote at the end of your README.

**Comment by tonyxiao** [comment]
This is no longer an issue since aws is now node 4
