### ISSUE TITLE
Suggested wiki edits

### ISSUE THREAD

**Issue by n8sabes** [Nopik/serverless-serve#3]
While it only took a few minutes to figure it out, here are two minor ReadMe wiki improvement suggestions based on my trial and error to get this up and running:
- Give a bit more context on where "path": "serverless-serve" sits in the JSON doc. You clearly and correctly state to insert within the table, but I missed that and replaced the table with curly braces. Maybe state "insert within the table braces" and show more context in the snippet:

```
  "plugins": [{
    "path": "serverless-serve"
  }]
```
- I used an IDE to edit the s-project.json rather than vi, so I did not issue a cd.. to step back up one level after npm install serverless-serve. sls serve start must be run from the main project directory, not the plugins directory, or it will error. Maybe add the following text.

From the main project directory (not the plugin directory), start the server.

```
sls serve start
```

**Comment by jagthedrummer** [comment]
I followed these instructions after the ones in the main README didn't work. Even then I'm still getting this error:

```
$ serverless serve start
WARNING: This plugin was requested by this project but could not be found: serverless-serve
{ [ServerlessError: Command Not Found] name: 'ServerlessError', messageId: 1 }
```

After a little trial and error I discovered that it would work if I manually created a directory at `plugins/node_modules` and then did `npm install serverless-serve` inside the `plugins` directory.

**Comment by mrtj** [comment]
@jagthedrummer I also had the same problem, that is caused by npm installing the node module to "../node_modules/serverless-serve" instead of "node_modules/serverless-serve", relative to the plugin folder. I did not understand really why, but after some retries npm started to install the plugin to the correct folder.

**Comment by Nopik** [comment]
Yeah, npm checks for `package.json` in current folder, and if there is none, but there is some `package.json` in parent folders, the parent folder is used as installation path. `npm install --prefix=.` forces to use current folder.

**Comment by Nopik** [comment]
Readme got updated.
