### ISSUE TITLE
Command to create tables in local DynamoDB

### ISSUE THREAD

**Issue by jagthedrummer** [Nopik/serverless-serve#6]
Using serverless-serve together with a local copy of DynamoDB has been working out great for me. I'd love to have some commands that would create/destroy tables in my local DynamoDB based on the resources described in `cloudformation/resources-cf.json`. Is that the sort of thing that would fit in this project as a helper function for running things locally, or should it be it's own plugin?

**Comment by Nopik** [comment]
Resource initialization like this is outside of this plugin. You need DynamoDB tables, somebody will need Postgres, somebody else will need to create gmail account. Serve plugin is for serving lambdas locally, and tries to do only that part. It allows you to specify custom init script, in which you can prepare stuff on the fly. Also, create/destroy tables seems more like one-time action, more suitable for standalone script.
