### ISSUE TITLE
process.cwd() should map to `project_root/back`

### ISSUE THREAD

**Issue by chadkouse** [Nopik/serverless-serve#7]
Ran into this while trying to use the node-config module https://github.com/lorenwest/node-config

To make it work with `sls serve` I have to put my config folder in my project root, however to make it work in aws lambda I have to put my config folder in `project_root/back` (which is the cwd when running on lambda)

What do you think?

**Comment by Nopik** [comment]
Well, serve plugin doesnt play with cwd at all, I guess you would need to ask serverless itself to change it. Also, you can create a workaround by doing some cd in custom init script (not so sure how it will work out), though.

Theoretically it should be possible to start serve plugin off any location within the project, though I never tried to do so.
